name: GeoCheck CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    # Por ahora solo instalará dependencias para ver que no haya errores
    # Más adelante activaremos el linter y los tests
    - run: npm init -y && npm install express